# Generated by Django 5.1.3 on 2024-11-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0002_alter_broker_creation_date_and_more'),
        ('parcel', '0004_alter_parcel_description_alter_parcel_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('price_per_meter', models.DecimalField(decimal_places=3, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('parcels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcel')),
            ],
        ),
    ]
