# Generated by Django 5.1.3 on 2024-11-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='parcels',
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_per_meter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
