# Generated by Django 5.1.3 on 2024-11-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_parcels_alter_offer_price_per_meter'),
        ('parcel', '0006_remove_parcel_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='parcels',
            field=models.ManyToManyField(to='parcel.parcel'),
        ),
    ]
