# Generated by Django 5.1.3 on 2024-11-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Personal', 'Personal'), ('Company', 'Company'), ('Governmental', 'Governmental')], max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='', max_length=500)),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('last_updated_date', models.DateTimeField()),
            ],
        ),
    ]
