# Generated by Django 5.1.3 on 2024-11-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
