# Generated by Django 5.1.3 on 2024-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('neighberhood', models.TextField()),
                ('subdivision_number', models.IntegerField()),
                ('land_use_group', models.CharField(choices=[('Agricultural', 'Agricultural'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
