# Generated by Django 5.1.3 on 2024-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='neighberhood',
            field=models.TextField(max_length=1000),
        ),
    ]
