# Generated by Django 5.1.3 on 2024-11-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_alter_parcel_neighberhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='neighberhood',
            new_name='neighborhood',
        ),
    ]
