# Generated by Django 5.1.3 on 2024-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_rename_neighberhood_parcel_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='neighborhood',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
