# Generated by Django 5.1.3 on 2024-11-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_parcels_alter_offer_price_per_meter'),
        ('parcel', '0004_alter_parcel_description_alter_parcel_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='offer.offer'),
        ),
    ]
