# Generated by Django 5.1.3 on 2024-11-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_parcel_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='offer',
        ),
    ]
